### ISSUE TITLE
[CLI] JSON Parsing Error

### ISSUE THREAD

**Issue by fclaerho** [jcsirot/JenGen#6]
The parser fails whereas the JSON is correct (using an online validator.)
## INPUT

<pre>
jenerator cat hello.json 
{
    "id": "com.example.hello",
    "name": "hello",
    "description": "blah!",
    "parameters": [],
    "command": "true"
}
</pre>

## OUTPUT

<pre>
jenerator java -jar jenerator-cli/target/jenerator-cli-1.0-SNAPSHOT.jar hello.json 
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 6 column 14 path $.command
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    at com.google.gson.Gson.fromJson(Gson.java:748)
    at com.chelonix.jenerator.cli.Main.main(Main.java:48)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 6 column 14 path $.command
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
    ... 5 more
</pre>

**Comment by jcsirot** [comment]
The JSON is not valid. "command" must be an object:

``` javascript
{
    "id": "com.example.hello",
    "name": "hello",
    "description": "blah!",
    "parameters": [],
    "command": {
        "executable": "true"
    }
}
```
